### PR TITLE
force parameter types

### PR DESCRIPTION
**Pull request by malkomes**
- TODO: change the `requirements.txt` before merging

### CODE REVIEW

**Review by harvey-intel — APPROVED** [review]
lgtm

**Comment by Chris-Sigopt** [comment]
Is the goal to replace all of the ValueErrors one type at a time with the appropriate SigoptValidationError? I'm not understanding why we now throw one InvalidTypeError and everything else is a ValueError.

**Comment by malkomes** [comment]
> Is the goal to replace all of the ValueErrors one type at a time with the appropriate SigoptValidationError? I'm not understanding why we now throw one InvalidTypeError and everything else is a ValueError.

yes @Chris-Sigopt that's my plan: replace all `ValueErrors` that we intentionally raise to the appropriate the `SigoptValidationError`; which means that we will be reserving the `stdlib` to exceptions that we didn't anticipate; but hopefully they will never happen 🤞

**Review by erichanslee — APPROVED** [review]
Thanks! 

Worth noting that you don't need to iterate over the list of parameter bounds since it's only two thins... you can just check them both manually. I don't think it'll be cleaner though, so fine  with things the way they're written

**Pull request merged**
